## Fonctionnel mais impossible d'installer des ipa sans jailbreak donc je désactive
name: Build IOS
run-name: Creating Production Ready 🚀

jobs:
  build:
    runs-on: macos-latest
    steps:
    -
      name: checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18.x

    - name: install dependencies
      run: npm ci

    - name: Install CocoaPods
      run: sudo gem install cocoapods

    - name: Create Build Folder
      run: npm run build-prod

    - name: Capacitor copy
      run: npx cap sync && cd ios/App && pod install

    - name: Build IPA
      run: cd ios/App && xcodebuild -workspace App.xcworkspace -scheme "App" -sdk iphoneos -configuration Debug -destination generic/platform=iOS archive CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
